class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.6.7.tar.gz"
  sha256 "98588667e0cae1be4e4f797bd1183c35d121b8e8451aff7ac77266bfd1d69c60"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "de9308ad1a26fa92f35bb3c207556f3c2383fa7a445c101ad3a9614fe48f9c12"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "6446affc510936fbb991b303240ec6151d3b33b71417e005a5775b53f7be2dde"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "3cd91adf224ae8867f2149ee4ae1111f9d84d3d9575718dcba4b5619ddcaa49a"
    sha256 cellar: :any_skip_relocation, sonoma:        "deddb08b144fcdc4fe29f834ddd11d8dae568bd80a37f770bcef9f8337903ca9"
    sha256 cellar: :any_skip_relocation, ventura:       "ace87cfbcea8a28ea2c9827637c6f34d8e806860c0428b833ca2d1c737d09089"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "cb0db45cf080589a49018e6ef1f6c04f00621b2c53d0db09ebb2b8cfbdb04001"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    system "cargo", "install", "--no-default-features", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
