class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.6.11.tar.gz"
  sha256 "cc7e74b1f706c3e7c8fba1b9f9c5d851d7c7fcda1b403d46aa83c5044e8b81e9"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "efa8774b756041d42e2cb270a6c3506e306a442ae15406e764b2d96a5e309e83"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "3e2817a037268316b695f7978faf2ca4ff761cf5b1c083326caac9f1f29c5ad7"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "1a28d482c0c81a80b0f2cea0ae4476c65afedd73522e8f7bad251f2ae2b09b6f"
    sha256 cellar: :any_skip_relocation, sonoma:        "3279dd12ccef72049ad6fa79409fc6104beecc092ee2cee12e188b7a75fae606"
    sha256 cellar: :any_skip_relocation, ventura:       "af9ab58831cab2a51555219f84d6a7fc9b7b0e66cc067ef7e429709db5787685"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "558808d8789c29103376ae74cc1057380f20508acf16e049d9a317db2dd6380d"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "005d0142986ec3719e5494c47b36626b2e42605c40cbbf63bd84eec51c9205ec"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    system "cargo", "install", "--no-default-features", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
