class Libmapper < Formula
  desc "Distributed system for media control mapping"
  homepage "http://www.libmapper.org"
  url "https://github.com/libmapper/libmapper/releases/download/2.4.10/libmapper-2.4.10.tar.gz"
  sha256 "e481912c491816359b8aca2ae0ea2b073bbe51fb6691e92d39ad848db93ed1e6"
  license "LGPL-2.1-or-later"

  bottle do
    sha256 cellar: :any,                 arm64_sonoma:   "165e054bcb7de8bc4d8af67224989dffda03d003272d2c104ddc63e17e021578"
    sha256 cellar: :any,                 arm64_ventura:  "b647984a373f82f5865afc97bd66b3777b7a4fc8d34cd0ea6e72572e0d704c8b"
    sha256 cellar: :any,                 arm64_monterey: "105b5ca0a00fc05e17d31fd8044f590df7f9b6aabbb1e80f45f723a9335332bf"
    sha256 cellar: :any,                 sonoma:         "4752c67cf956000d786522353cbf0d51856fb9302c25bcb512f0f425df5a7f1f"
    sha256 cellar: :any,                 ventura:        "acef52dc47ceefa462fe013b77071d9b49394b8613bb65538c860b505c5fa236"
    sha256 cellar: :any,                 monterey:       "41f0e09496c5a318c4dbaf8a5c5c9cc4a432a3e32104b00cb744b652d1267804"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "d17822a27b6232e4dde431d47aed20dcb445eb69d7fecdedf7733755e9d7c8c9"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
  depends_on "pkg-config" => :build
  depends_on "liblo"

  uses_from_macos "zlib"

  # version patch, upstream bug report, https://github.com/libmapper/libmapper/issues/106
  patch :DATA

  def install
    system "./configure", *std_configure_args
    system "make", "install"
  end

  test do
    (testpath/"test.c").write <<~EOS
      #include <stdio.h>
      #include "mapper/mapper.h"
      int main() {
        printf("%s", mpr_get_version());
        return 0;
      }
    EOS
    system ENV.cc, "test.c", "-L#{lib}", "-lmapper", "-o", "test"
    assert_match version.to_s, shell_output("./test")
  end
end

__END__
diff --git a/configure b/configure
index be1f37f..b29fb66 100755
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by GNU Autoconf 2.71 for libmapper 2.4.9.17+gf0e37ae5.
+# Generated by GNU Autoconf 2.71 for libmapper 2.4.10.
 #
 # Report bugs to <dot_mapper@googlegroups.com>.
 #
@@ -621,8 +621,8 @@ MAKEFLAGS=
 # Identity of this package.
 PACKAGE_NAME='libmapper'
 PACKAGE_TARNAME='libmapper'
-PACKAGE_VERSION='2.4.9.17+gf0e37ae5'
-PACKAGE_STRING='libmapper 2.4.9.17+gf0e37ae5'
+PACKAGE_VERSION='2.4.10'
+PACKAGE_STRING='libmapper 2.4.10'
 PACKAGE_BUGREPORT='dot_mapper@googlegroups.com'
 PACKAGE_URL='http://libmapper.org'
 
@@ -1435,7 +1435,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<_ACEOF
-\`configure' configures libmapper 2.4.9.17+gf0e37ae5 to adapt to many kinds of systems.
+\`configure' configures libmapper 2.4.10 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -1506,7 +1506,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of libmapper 2.4.9.17+gf0e37ae5:";;
+     short | recursive ) echo "Configuration of libmapper 2.4.10:";;
    esac
   cat <<\_ACEOF
 
@@ -1644,7 +1644,7 @@ fi
 test -n "$ac_init_help" && exit $ac_status
 if $ac_init_version; then
   cat <<\_ACEOF
-libmapper configure 2.4.9.17+gf0e37ae5
+libmapper configure 2.4.10
 generated by GNU Autoconf 2.71
 
 Copyright (C) 2021 Free Software Foundation, Inc.
@@ -2043,7 +2043,7 @@ cat >config.log <<_ACEOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by libmapper $as_me 2.4.9.17+gf0e37ae5, which was
+It was created by libmapper $as_me 2.4.10, which was
 generated by GNU Autoconf 2.71.  Invocation command line was
 
   $ $0$ac_configure_args_raw
@@ -3549,7 +3549,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE='libmapper'
- VERSION='2.4.9.17+gf0e37ae5'
+ VERSION='2.4.10'
 
 
 printf "%s\n" "#define PACKAGE \"$PACKAGE\"" >>confdefs.h
@@ -20728,7 +20728,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF || ac_write_fail=1
 # report actual input values of CONFIG_FILES etc. instead of their
 # values after options handling.
 ac_log="
-This file was extended by libmapper $as_me 2.4.9.17+gf0e37ae5, which was
+This file was extended by libmapper $as_me 2.4.10, which was
 generated by GNU Autoconf 2.71.  Invocation command line was
 
   CONFIG_FILES    = $CONFIG_FILES
@@ -20801,7 +20801,7 @@ ac_cs_config_escaped=`printf "%s\n" "$ac_cs_config" | sed "s/^ //; s/'/'\\\\\\\\
 cat >>$CONFIG_STATUS <<_ACEOF || ac_write_fail=1
 ac_cs_config='$ac_cs_config_escaped'
 ac_cs_version="\\
-libmapper config.status 2.4.9.17+gf0e37ae5
+libmapper config.status 2.4.10
 configured by $0, generated by GNU Autoconf 2.71,
   with options \\"\$ac_cs_config\\"
 
@@ -22828,4 +22828,3 @@ then :
 fi
 echo "version                     " $PACKAGE_VERSION
 echo --------------------------------------------------
-
