class Typical < Formula
  desc "Data interchange with algebraic data types"
  homepage "https://github.com/stepchowfun/typical"
  url "https://github.com/stepchowfun/typical/archive/refs/tags/v0.12.0.tar.gz"
  sha256 "f469e5dc2934f48be2b068ae9f5ec6ef7e4e52915260034848a568870a41ad3c"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "5c62113b5ed736a32c990e9688f2b83980e3f64f78c5a6d13633a431c3f00fa9"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "621f76bebf2cea1e1ef905e77702da71a1baf5ad9050e1f9e7881faa5c73c905"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "d47072d2de55c02c05e61aab154336d21798cfba7e1023d5f292315f83cfbcaa"
    sha256 cellar: :any_skip_relocation, sonoma:         "c2957b22a993c849d2468d5d0a3ee194470320dfe366d8e89f600657554fd98b"
    sha256 cellar: :any_skip_relocation, ventura:        "b53a707d94102da770e729f74560ef2233e6ecf8d4e5f51635df19e151aeea88"
    sha256 cellar: :any_skip_relocation, monterey:       "447dfcfde34b239122611ffb5fb87a5ab16657d7e0417856f84f702f40ba5591"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "7f1f18c33b014434eb7b36fd5808485ed4d6dc8424d68769a78ef3772c3750df"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"types.t").write <<~EOS
      struct SendEmailRequest {
          to: String = 0
          subject: String = 1
          body: String = 2
      }

      choice SendEmailResponse {
          success = 0
          error: String = 1
      }
    EOS

    assert_empty shell_output("#{bin}/typical generate types.t --rust types.rs --typescript types.ts")

    generated_rust_code = (testpath/"types.rs").read
    generated_typescript_code = (testpath/"types.ts").read

    assert_match "// This file was automatically generated by Typical", generated_rust_code
    assert_match "pub struct SendEmailRequestIn", generated_rust_code
    assert_match "pub struct SendEmailRequestOut", generated_rust_code
    assert_match "pub enum SendEmailResponseIn", generated_rust_code
    assert_match "pub enum SendEmailResponseOut", generated_rust_code
    assert_match "// This file was automatically generated by Typical", generated_typescript_code
    assert_match "export type SendEmailRequestIn", generated_typescript_code
    assert_match "export type SendEmailRequestOut", generated_typescript_code
    assert_match "export type SendEmailResponseIn", generated_typescript_code
    assert_match "export type SendEmailResponseOut", generated_typescript_code
  end
end
